cam_0:
  cam_model: Pinhole
  cam_width: 1280
  cam_height: 1024
  scale: 0.5
  cam_fx: 1176.2874292149932
  cam_fy: 1176.21585445307
  cam_cx: 592.1187382755453
  cam_cy: 509.0864309628322
  cam_d0: -0.13218037625958456
  cam_d1: 0.15360732717073536
  cam_d2: 0.00036918417348059815
  cam_d3: -0.00031715324469463964
#
#  cam_width: 1280
#  cam_height: 1024
#  scale: 0.5
#  cam_fx: 1311.89517127580
#  cam_fy: 1311.36488586115
#  cam_cx: 656.523841857393
#  cam_cy: 504.136322840350
#  cam_d0: -0.0780830982640722
#  cam_d1: 0.146382433670493
#  cam_d2: -0.00110111633050301
#  cam_d3: -0.00110752991013068